Annotation Extraction
eclipse/ice pull request #474
Opened 2020-10-12 21:41 UTC by dbluhm

This PR builds on top of Michael's changes for annotation extraction. This represents an attempt to simplify and preserve type safety while also clearly defining roles of different aspects of the code.

Notably, this PR introduces the AnnotationExtractor and GeneratedFileWriter interfaces and reworks the WriterGenerator interface to clearly define what kind of data is extracted and processed.

Open to feedback :slightly_smiling_face:

2020-10-12 21:42 UTC, dbluhm commented
Given the commit history is quite long and contains commit messages clearly intended as WIP, when the time comes, squash-merging this PR seems like a good idea.

2020-10-13 13:04 UTC, jayjaybillings commented
Thanks. I'll start looking it through. A few things to get started:
1) I don't think we should squash the history. I prefer all the gory details.
2) I would like to setup a time with you to look through questions I have about this. If @walshmm can join that would be good too.
3) Have you considered putting together a short HOWTO, README, or tutorial that explains how this would be used? That would help me understand whether or not we've created something that is actually useful and simple for implementing new annotations.

Based on a cursory scan, if we can work through #s 2 and 3 I in principal don't see anything that will prevent us from closing this quickly.

2020-10-13 13:27 UTC, dbluhm commented
1. Sounds good :slightly_smiling_face: 
2. Sounds good again
3. I'll add a README -- intended to and promptly forgot.

2020-10-13 13:34 UTC, walshmm commented
2. Just let me know when. :+1:

2020-10-13 14:00 UTC, jayjaybillings requested changes
Looks good. This is nice work. Minor changes requested. Also, what's the level of test coverage?

2020-10-13 14:23 UTC, dbluhm commented on org.eclipse.ice.dev/org.eclipse.ice.dev.annotations/src/main/java/org/eclipse/ice/dev/annotations/processors/DataElementExtractor.java
> +			.build();
The debugger doesn't like direct returns but then Sonar Lint doesn't like "unnecessary intermediate values." I assume we prefer better debugging over Sonar's rule here?

2020-10-13 14:53 UTC, dbluhm commented on org.eclipse.ice.dev/org.eclipse.ice.dev.annotations/src/main/java/org/eclipse/ice/dev/annotations/processors/AnnotationExtractor.java
> +	}
This made me take another look at `AnnotatedElement`. I think we can collapse a lot of those helpers into the `AbstractAnnotationExtractor` as well. Feels like a better fit than a wrapper around Element.

2020-10-13 20:23 UTC, dbluhm commented
> Looks good. This is nice work. Minor changes requested. Also, what's the level of test coverage?

With lombok influencing my coverage it's hard to say exactly what percentage but after removing lombok builders from the coverage (so there would still be equals, hashcode, nonnull, etc.) we're around 90%

2020-10-22 21:45 UTC, jayjaybillings approved these changes
Thanks for the changes. This looks excellent. Approved from a code perspective. I'll check my other notes in the ticket.

2020-10-22 21:47 UTC, jayjaybillings commented
> * Sounds good 🙂
> 
> * Sounds good again
> 
> * I'll add a README -- intended to and promptly forgot.

How's the README going? The code looks good and I'm ready to merge. Should we still meet? If so, will @walshmm be joining us?

2020-10-22 22:41 UTC, dbluhm commented
> How's the README going? The code looks good and I'm ready to merge. Should we still meet? If so, will @walshmm be joining us?

README is coming along, I've ended up putting more effort into it than I anticipated it would need and even had some interesting questions raised from the exercise of writing a demo processor with all the bits and pieces. From a code perspective, I think this is feature complete. The questions I raised for myself are future work that would build off of what is already present so I think those are best suited for separate PR(s).

2020-10-22 22:44 UTC, dbluhm commented
And I'm still good to meet and discuss changes whenever!

2020-10-23 13:32 UTC, jayjaybillings commented
Okay, let's catch up in Mattermost about picking a date to talk.

2020-10-23 13:36 UTC, jayjaybillings commented
Nevermind - I don't think we need to meet to discuss it. I think you addressed all of my questions already. As soon as you push the README, I'll merge it (or you can). Nice work.

2020-10-23 16:44 UTC, jayjaybillings approved these changes
Approved. Good work.

2020-10-23 16:45 UTC, jayjaybillings commented
Two things:
1) Can you fix the conflict?
2) Can you fix your history?

Otherwise, ready to merge.

2020-10-23 17:29 UTC, dbluhm commented
After a mess of force pushes, I think we're just going to have to wait for the ECA bot to update after I had to fiddle around with my email associated with my Eclipse Foundation account for EclipseCon. If I had to guess, it seems that it must update on a daily cron job or something as after a few hours it still hasn't updated. I'll check back in tomorrow and ask the bot to revalidate and hopefully everything will be sorted then.

2020-10-23 17:31 UTC, merged